<!--
 * @Author: liwz
 * @Date: 2024-09-23 14:47:42
 * @LastEditors: liwz
 * @LastEditTime: 2024-09-23 15:00:36
 * @FilePath: /study_new/promise/02-Promise的API/02-Promise.resolve.html
 * @Description:
 *
 * Copyright (c) 2024 by ${git_name_email}, All Rights Reserved.
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>02-Promise.resolve</title>
  </head>
  <body>
    <script>
      let p1 = Promise.resolve(23)
      console.log(p1)

      let p2 = Promise.resolve(
        new Promise((resolve, reject) => {
          // resolve('ok')
          reject('Error')
        })
      )
      console.log(p2)
      // 使用p2.catch可以预防控制台出错
      p2.catch(err => {
        console.log('err: ', err)
      })
    </script>
  </body>
</html>
